[workspace]
members = [
    "openapi",
    "bench/binary_size",
]

[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.12.1"
description = "API bindings for the Stripe v1 HTTP API"
authors = [
  "Anna Baldwin <abaldwin@developers.wyyerd.com>",
  "Kevin Stenerson <kstenerson@developers.wyyerd.com>"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/wyyerd/stripe-rs"
documentation = "https://docs.rs/stripe-rust"
keywords = ["stripe", "v1", "api"]
categories = ["api-bindings"]
edition = "2018"

[badges]
travis-ci = {repository = "wyyerd/stripe-rs"}

[lib]
name = "stripe"

[features]
default = ["full", "webhook-events", "blocking", "hyper_tls"]
full = [
#    "core",
#    "payment-methods",
    "checkout",
    "billing",
    "connect",
    "fraud",
    "issuing",
    "orders",
    "sigma",
    "webhook-endpoints",
]

# Stripe feature groups
#core = [] # N.B. always enabled for now
#payment-methods = [] # N.B. always enabled for now
checkout = []
billing = []
connect = []
fraud = []
issuing = []
orders = []
sigma = []
webhook-endpoints = []

# Deserialize events from webhooks
webhook-events = ["events", "hmac", "sha2"]
events = []

# Deprecated. Use either `webhook-events` or `webhook-endpoints` instead.
webhooks = ["webhook-endpoints", "webhook-events"]

# hyper_tls or hyper_rustls
hyper_tls = ["hyper_tls"]
hyper_rustls = ["hyper_rustls"]

# Enable the blocking client
blocking = ["tokio/rt-core"]
async = []

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures-util = { version = "0.3.1", default-features = false }
http = "0.2.0"
hyper = { version = "0.13", default-features = false, features = ["tcp"] }
serde = "1.0.79" # N.B. we use `serde(other)` which was introduced in `1.0.79`
serde_derive = "1.0.79"
serde_json = "1.0"
serde_qs = "0.4"
smol_str = "0.1.10"
tokio = { version = "0.2.0", default-features = false, features = ["tcp", "time"] }

# Webhook support
hmac = { version = "0.6", optional = true }
sha2 = { version = "0.7", optional = true }

# Native Vs Rustls TLS
hyper-tls = { version = "0.4.0", optional = true }
hyper-rustls = { version = "0.20", optional = true }

[[example]]
name = "async_create_charge"
required-features = ["async"]

[dev-dependencies]
lazy_static = "1.3.0"
tokio = { version = "0.2", features = ["full"] }
