[workspace]
members = [
    "openapi",
    "bench/binary_size",
]

[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.13.0-dev"
description = "API bindings for the Stripe HTTP API"
authors = [
  "Anna Baldwin <abaldwin@developers.wyyerd.com>",
  "Kevin Stenerson <kestred@users.noreply.github.com>"
]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/wyyerd/stripe-rs"
repository = "https://github.com/wyyerd/stripe-rs"
documentation = "https://docs.rs/stripe-rust"
keywords = ["stripe", "v1", "api"]
categories = ["api-bindings"]
edition = "2018"

[badges]
travis-ci = {repository = "wyyerd/stripe-rs"}

[lib]
name = "stripe"

[features]
default = ["full", "webhook-events", "default-tls"]
full = [
#    "core",
#    "payment-methods",
    "checkout",
    "billing",
    "connect",
    "fraud",
    "issuing",
    "orders",
    "sigma",
    "webhook-endpoints",
]

# Stripe feature groups
#core = [] # N.B. always enabled for now
#payment-methods = [] # N.B. always enabled for now
checkout = []
billing = []
connect = []
fraud = []
issuing = []
orders = []
sigma = []
webhook-endpoints = []

# Deserialize events from webhooks
webhook-events = ["events", "hmac", "sha2"]
events = []

# Enable the blocking client
blocking = ["tokio/rt-core"]

default-tls = ["hyper-tls"]
rustls-tls = ["hyper-rustls"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures-util = { version = "0.3", default-features = false }
http = "0.2"
hyper = { version = "0.13", default-features = false, features = ["tcp"] }
hyper-tls = { version = "0.4", optional = true }
hyper-rustls = { version = "0.20", optional = true }
serde = "=1.0.118" # N.B. we use `serde(other)` which was introduced in `1.0.79`
serde_derive = "=1.0.118"
serde_json = "1.0"
serde_qs = "0.5"
smol_str = "0.1"
tokio = { version = "0.2", default-features = false, features = ["tcp", "time"] }

# Webhook support
hmac = { version = "0.7", optional = true }
sha2 = { version = "0.8", optional = true }

[[example]]
name = "async_create_charge"
#required-features = ["async"]

[[example]]
name = "create_charge"
required-features = ["blocking"]

[[example]]
name = "create_customer"
required-features = ["blocking"]

[[example]]
name = "create_customer_with_source"
required-features = ["blocking"]

[[example]]
name = "list_customers"
required-features = ["blocking"]

[dev-dependencies]
lazy_static = "1.4.0"
tokio = { version = "0.2", features = ["full"] }
